instruments = [
    'Bass',
    'Bassoon',
    'Cello',
    'Clarinet, B-flat',
    'Clarinet,E-flat',
    'Clarinet, Bass',
    'Euphonium',
    'Flute',
    'Guitar',
    'Harp',
    'Harpsichord',
    'Horn in F',
    'Horn in B-flat',
    'Mandolin',
    'Oboe',
    'Organ',
    'Percussion',
    'Piano',
    'Piccolo',
    'Saxophone, Soprano',
    'Saxophone, Alto',
    'Saxophone, Tenor',
    'Saxophone, Baritone',
    'Theremin',
    'Trombone',
    'Trombone, Bass',
    'Trumpet',
    'Tuba',
    'Viola',
    'Violin',
    'Voice, Soprano',
    'Voice, Alto',
    'Voice, Tenor',
    'Voice, Baritone',
    'Voice, Bass',
]