test_users = [
    {
        "first_name": "Frank",
        "last_name": "Huang",
        "email": "frank@huang.com",
        "street_address": "123 Dover St",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77005",
        "phone_number": "7131111111",
        "bio": "Some bio",
        "rating": 5,
        "is_coach": False,
    },
    {
        "first_name": "Sheryl",
        "last_name": "Staples",
        "email": "sheryl@staples.com",
        "street_address": "456 Elephant Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77024",
        "phone_number": "8322222222",
        "bio": "Some bio",
        "rating": 2,
        "is_coach": False,
    },
    {
        "first_name": "Michelle",
        "last_name": "Kim",
        "email": "michelle@kim.com",
        "street_address": "57 Bobcat Ln",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77044",
        "phone_number": "7133333333",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Quan",
        "last_name": "Ge",
        "email": "quan@ge.com",
        "street_address": "9736 Hummingbird Re",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77035",
        "phone_number": "8323333333",
        "bio": "Some bio",
        "rating": 7,
        "is_coach": False,
    },
    {
        "first_name": "Kerry",
        "last_name": "McDermott",
        "email": "kerry@mcdermott.com",
        "street_address": "735 Buffalo Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77045",
        "phone_number": "7135555555",
        "bio": "Some bio",
        "rating": 3,
        "is_coach": False,
    },
    {
        "first_name": "Anna",
        "last_name": "Rabinova",
        "email": "anna@rabinova.com",
        "street_address": "672 Egret Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77005",
        "phone_number": "7136666666",
        "bio": "Some bio",
        "rating": 4,
        "is_coach": False,
    },
    {
        "first_name": "Fiona",
        "last_name": "Simon",
        "email": "fiona@simon.com",
        "street_address": "176 Heron Ln",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77026",
        "phone_number": "8329999999",
        "bio": "Some bio",
        "rating": 4,
        "is_coach": False,
    },
    {
        "first_name": "Sharon",
        "last_name": "Yamada",
        "email": "sharon@yamada.com",
        "street_address": "12 Tabasco Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77001",
        "phone_number": "7136666666",
        "bio": "Some bio",
        "rating": 2,
        "is_coach": False,
    },
    {
        "first_name": "Elizabeth",
        "last_name": "Zeltser",
        "email": "elizabeth@zeltser.com",
        "street_address": "2700 Kingfisher Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77005",
        "phone_number": "8324444444",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Lisa",
        "last_name": "Kim",
        "email": "lisa@kim.com",
        "street_address": "999 Tamale Ln",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77025",
        "phone_number": "8323454557",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Marilyn",
        "last_name": "Dubow",
        "email": "marilyn@dubow.com",
        "street_address": "467 Panther St",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77007",
        "phone_number": "7134568976",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Andi",
        "last_name": "Zhang",
        "email": "andi@zhang.com",
        "street_address": "1200 Catfish Ln #2B",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77056",
        "phone_number": "8327689857",
        "bio": "Some bio",
        "rating": 7,
        "is_coach": False,
    },
    {
        "first_name": "Cynthia",
        "last_name": "Phelps",
        "email": "cynthia@phelps.com",
        "street_address": "4 Privet dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77045",
        "phone_number": "8325679876",
        "bio": "Some bio",
        "rating": 7,
        "is_coach": False,
    },
    {
        "first_name": "Rebecca",
        "last_name": "Young",
        "email": "rebecca@young.com",
        "street_address": "97 Blunderbuss Ln",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77088",
        "phone_number": "7135679876",
        "bio": "Some bio",
        "rating": 3,
        "is_coach": False,
    },
    {
        "first_name": "Cong",
        "last_name": "Wu",
        "email": "cong@wu.com",
        "street_address": "333 Shasta Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77024",
        "phone_number": "8326782345",
        "bio": "Some bio",
        "rating": 7,
        "is_coach": False,
    },
    {
        "first_name": "Dorian",
        "last_name": "Rence",
        "email": "dorian@rence.com",
        "street_address": "713 Harris Rd",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77043",
        "phone_number": "7135679876",
        "bio": "Some bio",
        "rating": 4,
        "is_coach": False,
    },
    {
        "first_name": "Leah",
        "last_name": "Ferguson",
        "email": "leah@ferguson.com",
        "street_address": "777 Katy Freeway #710",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77025",
        "phone_number": "8325678765",
        "bio": "Some bio",
        "rating": 0,
        "is_coach": True,
    },
    {
        "first_name": "Katherine",
        "last_name": "Greene",
        "email": "katherine@greene.com",
        "street_address": "845 Longbow Ln",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77045",
        "phone_number": "7137651234",
        "bio": "Some bio",
        "rating": 1,
        "is_coach": False,
    },
    {
        "first_name": "Vivek",
        "last_name": "Kamath",
        "email": "vivek@kamath.com",
        "street_address": "912 Gravity Rd",
        "city": "Katy",
        "state": "TX",
        "zip_code": "77987",
        "phone_number": "8325679876",
        "bio": "Some bio",
        "rating": 1,
        "is_coach": False,
    },
    {
        "first_name": "Peter",
        "last_name": "Kenote",
        "email": "peter@kenote.com",
        "street_address": "33 Lakeview Dr",
        "city": "Sugarland",
        "state": "TX",
        "zip_code": "77099",
        "phone_number": "7135678765",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Kenneth",
        "last_name": "Mirkin",
        "email": "kenneth@mirkin.com",
        "street_address": "917 Hedgehog Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77024",
        "phone_number": "8321239876",
        "bio": "Some bio",
        "rating": 5,
        "is_coach": False,
    },
    {
        "first_name": "Judith",
        "last_name": "Nelson",
        "email": "judith@nelson.com",
        "street_address": "555 Times Ave #3100",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77067",
        "phone_number": "7132345678",
        "bio": "Some bio",
        "rating": 2,
        "is_coach": False,
    },
    {
        "first_name": "R\u00c3\u00a9mi",
        "last_name": "Pelletier",
        "email": "remi@pelletier.com",
        "street_address": "445 King Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77035",
        "phone_number": "8327659876",
        "bio": "Some bio",
        "rating": 1,
        "is_coach": False,
    },
    {
        "first_name": "Robert",
        "last_name": "Rinehart",
        "email": "robert@rinehart.com",
        "street_address": "897 Butler Blvd Unit C",
        "city": "Humble",
        "state": "TX",
        "zip_code": "77099",
        "phone_number": "7136781356",
        "bio": "Some bio",
        "rating": 1,
        "is_coach": False,
    },
    {
        "first_name": "Carter",
        "last_name": "Brey",
        "email": "carter@brey.com",
        "street_address": "888 Rice Blvd",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77055",
        "phone_number": "8328763456",
        "bio": "Some bio",
        "rating": 3,
        "is_coach": False,
    },
    {
        "first_name": "Eileen",
        "last_name": "Moon-Myers",
        "email": "eileen@moonmyers.com",
        "street_address": "8989 Moonview Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77035",
        "phone_number": "7138763456",
        "bio": "Some bio",
        "rating": 4,
        "is_coach": False,
    },
    {
        "first_name": "Eric",
        "last_name": "Bartlett",
        "email": "eric@bartlett.com",
        "street_address": "9876 Dove Rd #5",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77044",
        "phone_number": "8326541234",
        "bio": "Some bio",
        "rating": 0,
        "is_coach": True,
    },
    {
        "first_name": "Elizabeth",
        "last_name": "Dyson",
        "email": "elizabeth@dyson.com",
        "street_address": "127 Eggplant Ave",
        "city": "Beaumont",
        "state": "TX",
        "zip_code": "79124",
        "phone_number": "7139873456",
        "bio": "Some bio",
        "rating": 4,
        "is_coach": False,
    },
    {
        "first_name": "Alex",
        "last_name": "Gonzales",
        "email": "alex@gonzales.com",
        "street_address": "27 Clover Ln",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77098",
        "phone_number": "8327868876",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Sal",
        "last_name": "Capone",
        "email": "sal@capone.com",
        "street_address": "555 Crumpet Rd",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77034",
        "phone_number": "7139874567",
        "bio": "Some bio",
        "rating": 2,
        "is_coach": False,
    },
    {
        "first_name": "Maria",
        "last_name": "Kitsopoulos",
        "email": "maria@kitsopoulos.com",
        "street_address": "786 Barber St",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77055",
        "phone_number": "8327896543",
        "bio": "Some bio",
        "rating": 2,
        "is_coach": False,
    },
    {
        "first_name": "Nathan",
        "last_name": "Vickery",
        "email": "nathan@vickery.com",
        "street_address": "222 Takemori Rd",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77027",
        "phone_number": "8327652468",
        "bio": "Some bio",
        "rating": 3,
        "is_coach": False,
    },
    {
        "first_name": "Ba",
        "last_name": "Nguyen",
        "email": "ba@nguyen.com",
        "street_address": "5757 Desplatt Blvd #3C",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77055",
        "phone_number": "7139872468",
        "bio": "Some bio",
        "rating": 3,
        "is_coach": False,
    },
    {
        "first_name": "Timothy",
        "last_name": "Cobb",
        "email": "timothy@cobb.com",
        "street_address": "92 Longshadows Ln",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77035",
        "phone_number": "8327651357",
        "bio": "Some bio",
        "rating": 3,
        "is_coach": False,
    },
    {
        "first_name": "Max",
        "last_name": "Zeugner",
        "email": "max@zeugner.com",
        "street_address": "93 Cobblestone Rd",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77056",
        "phone_number": "7139872468",
        "bio": "Some bio",
        "rating": 2,
        "is_coach": False,
    },
    {
        "first_name": "Blake",
        "last_name": "Hinson",
        "email": "blake@hinson.com",
        "street_address": "1234 Harpoon St",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77067",
        "phone_number": "8328762345",
        "bio": "Some bio",
        "rating": 1,
        "is_coach": False,
    },
    {
        "first_name": "Satoshi",
        "last_name": "Okamoto",
        "email": "satoshi@okomoto.com",
        "street_address": "6500 Ave B",
        "city": "Spring",
        "state": "TX",
        "zip_code": "78072",
        "phone_number": "7138762468",
        "bio": "Some bio",
        "rating": 4,
        "is_coach": False,
    },
    {
        "first_name": "Randall",
        "last_name": "Butler",
        "email": "randall@butler.com",
        "street_address": "1212 Grapefruit Ln",
        "city": "Bellaire",
        "state": "TX",
        "zip_code": "77045",
        "phone_number": "8329751357",
        "bio": "Some bio",
        "rating": 5,
        "is_coach": False,
    },
    {
        "first_name": "David",
        "last_name": "J.",
        "email": "david@grossman.com",
        "street_address": "8900 Sugarfoot Rd",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77022",
        "phone_number": "7137652345",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Mindy",
        "last_name": "Kaufman",
        "email": "mindy@kaufman.com",
        "street_address": "67 Golfview Terr",
        "city": "Spring",
        "state": "TX",
        "zip_code": "77999",
        "phone_number": "8327892345",
        "bio": "Some bio",
        "rating": 6,
        "is_coach": False,
    },
    {
        "first_name": "Sherry",
        "last_name": "Sylar",
        "email": "sherry@sylar.com",
        "street_address": "4622 Kingfisher Dr",
        "city": "Houston",
        "state": "TX",
        "zip_code": "77035",
        "phone_number": "7138764567",
        "bio": "Some bio",
        "rating": 5,
        "is_coach": False,
    },
]
