# Generated by Django 2.1.1 on 2019-01-04 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instruments', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=25, verbose_name='Last Name')),
                ('street_address', models.CharField(max_length=25)),
                ('unit_number', models.CharField(max_length=25, null=True)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=5)),
                ('phone_number', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('password', models.TextField()),
                ('is_coach', models.BooleanField(default=False, verbose_name='Is a coach')),
                ('bio', models.TextField()),
                ('rating', models.CharField(max_length=250, verbose_name='Skill Rating')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Has been approved')),
                ('is_reviewed', models.BooleanField(default=False, verbose_name='Has been viewed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Application Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated')),
                ('primary_instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='instruments.Instrument')),
                ('second_instrument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secondary_users', to='instruments.Instrument')),
            ],
        ),
        migrations.CreateModel(
            name='Patron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone_number', models.CharField(max_length=10)),
                ('street_address', models.CharField(max_length=25)),
                ('unit_number', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
