# Generated by Django 2.1.1 on 2018-12-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='unit_number',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
